services:
  app:
    build:
      context: ./docker/php
    container_name: laravel_app
    volumes:
      - ./:/var/www/html
    networks:
      - laravel
    depends_on:
      - db

  nginx:
    image: nginx:1.27-alpine
    container_name: laravel_nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

  node:
    image: node:20
    container_name: laravel_node
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - "5173:5173" # se usar vite
    command: sh -c "npm install && npm run dev"
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin:5.2
    container_name: laravel_phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db       # nome do serviço MySQL no docker-compose
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    networks:
      - laravel

networks:
  laravel:

volumes:
  dbdata:
